### ISSUE TITLE
Getting this error with example

### ISSUE THREAD

**Issue by inluxc** [stepci/runner#100]
```
    snippet: ' 2 | \n' +
      ' 3 | // Example workflow\n' +
      ' 4 | const workflow = {\n' +
      ' 5 |     version: "1.0",\n' +
      '----------------^\n' +
      ' 6 |     name: "Status Test",\n' +
      ' 7 |     env: {'

```

**Comment by mishushakov** [comment]
Sorry, can you provide the full workflow?

**Comment by inluxc** [comment]
```
import { run } from '@stepci/runner'
import { EventEmitter } from 'node:events'

// Example workflow
const workflow = {
  version: "1.0",
  name: "Status Test",
  env: {
    host: "example.com"
  },
  tests: {
    example: {
      steps: [{
        name: "GET request",
        http: {
          url: "https://{{env.host}}",
          method: "GET",
          check: {
            status: "/^20/"
          }
        }
      }]
    }
  }
}

const ee = new EventEmitter()
ee.on('done', console.log)
run(workflow, { ee })
```

Node -v: v16.18.1

**Comment by mishushakov** [comment]
Ah yeah, I see that. Thanks for pointing it out!
The docs for the runner are outdated. We changed the variable syntax from {{variable}} to ${{ variable }. I will close the issue as resolved for now and create a new one to update the documentation

Thanks for your help 🙏

**Comment by inluxc** [comment]
Hi there i know you closed the issue but o still getting the same error.. 

```
import {run} from '@stepci/runner'
import {EventEmitter} from 'node:events'

// Example workflow
const workflow = {
    version: "1.0",
    name: "Status Test",
    env: {
        host: process.env.BASE_URL,
        storeID: process.env.STOREID,
        clientSecret: process.env.CLIENTSECRET
    },
    component: {
        credentials: {
            oauth: {
                endpoint: "https://${{env.host}}/connect/token",
                grant_type: "client_credentials",
                scope: "api.retailer",
                client_id: "${{env.storeID}}",
                client_secret: "${{env.clientSecret}}"
            }
        },
        tests: {
            example: {
                steps: [{
                    name: "GET request",
                    http: {
                        url: "https://${{env.host}}/api/v2.0/stores",
                        method: "GET",
                        check: {
                            status: "/^20/"
                        }
                    }
                }]
            }
        }
    }
}

const ee = new EventEmitter()
ee.on('done', console.log)
run(workflow, {ee})
```

Can check what's wrong with that?

**Comment by mishushakov** [comment]
Does your first example work when you change`"https://{{env.host}}"`  to `"https://${{env.host}}"`?

**Comment by inluxc** [comment]
No it does not work, still the same error.
Full output:

```
/home/fulvio/.nvm/versions/node/v16.18.1/lib/node_modules/stepci/node_modules/js-yaml/lib/loader.js:183
  return new YAMLException(message, mark);
         ^
YAMLException: end of the stream or a document separator is expected (6:12)

 3 | 
 4 | // Example workflow
 5 | const workflow = {
 6 |     version: "1.0",
----------------^
 7 |     name: "Status Test",
 8 |     env: {
    at generateError (/home/fulvio/.nvm/versions/node/v16.18.1/lib/node_modules/stepci/node_modules/js-yaml/lib/loader.js:183:10)
    at throwError (/home/fulvio/.nvm/versions/node/v16.18.1/lib/node_modules/stepci/node_modules/js-yaml/lib/loader.js:187:9)
    at readDocument (/home/fulvio/.nvm/versions/node/v16.18.1/lib/node_modules/stepci/node_modules/js-yaml/lib/loader.js:1645:5)
    at loadDocuments (/home/fulvio/.nvm/versions/node/v16.18.1/lib/node_modules/stepci/node_modules/js-yaml/lib/loader.js:1688:5)
    at Object.load (/home/fulvio/.nvm/versions/node/v16.18.1/lib/node_modules/stepci/node_modules/js-yaml/lib/loader.js:1714:19)
    at runFromFile (/home/fulvio/.nvm/versions/node/v16.18.1/lib/node_modules/stepci/node_modules/@stepci/runner/dist/index.js:63:38) {
  reason: 'end of the stream or a document separator is expected',
  mark: {
    name: null,
    buffer: "import { run } from '@stepci/runner'\n" +
      "import { EventEmitter } from 'node:events'\n" +
      '\n' +
      '// Example workflow\n' +
      'const workflow = {\n' +
      '    version: "1.0",\n' +
      '    name: "Status Test",\n' +
      '    env: {\n' +
      '        host: "example.com"\n' +
      '    },\n' +
      '    tests: {\n' +
      '        example: {\n' +
      '            steps: [{\n' +
      '                name: "GET request",\n' +
      '                http: {\n' +
      '                    url: "https://${{env.host}}",\n' +
      '                    method: "GET",\n' +
      '                    check: {\n' +
      '                        status: "/^20/"\n' +
      '                    }\n' +
      '                }\n' +
      '            }]\n' +
      '        }\n' +
      '    }\n' +
      '}\n' +
      '\n' +
      'const ee = new EventEmitter()\n' +
      "ee.on('done', console.log)\n" +
      'run(workflow, { ee })\n',
    position: 131,
    line: 5,
    column: 11,
    snippet: ' 3 | \n' +
      ' 4 | // Example workflow\n' +
      ' 5 | const workflow = {\n' +
      ' 6 |     version: "1.0",\n' +
      '----------------^\n' +
      ' 7 |     name: "Status Test",\n' +
      ' 8 |     env: {'
  }
}
```

**Comment by inluxc** [comment]
Forget it found out why, me dumm.. :smiling_face_with_tear: 

It works, for same reason, num run command was with stepCI instead of node.
Thanks

**Comment by mishushakov** [comment]
Glad the issue is resolved for you! Let us know if you have any other issues or leave your feedback on https://step.ci/feedbacl
